version: '3.8'
services:
  build:
    image: ${IMAGE}:${TAG}
    build:
      context: ../../
      dockerfile: .deploy/backend/Dockerfile

  server:
    image: ${IMAGE}:${TAG}
    ports:
      - 3333:3333
