name: nx-backend deploy manually
on:
  workflow_dispatch:
jobs:
  nx-backend-deploy:
    needs:
      - nx-backend-build
    runs-on:
      - self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker run
        run: |
          docker ps -q --filter "name=nx-backend" | grep -q . && docker stop nx-backend && docker rm -fv nx-backend
          docker run -d -p 3333:3333 --name nx-backend --restart always cheolcheol/nx-backend:latest
